### ISSUE TITLE
Task: Host Server and database

### ISSUE THREAD

**Issue by lfb0801** [travel-manager/server#12]
- [x] `Ubuntu server`
- [x] `Assign admin permissions`
- [x] `Install MVC, Java, Spring Boot`
- [x] `Install & Configure PhpMyAdmin`

**Comment by ReneRoets** [comment]
- [ ] `Ubuntu server`
- [ ] `Assign admin permissions`
- [ ] `Install MVC, Java, Spring Boot`
- [ ] `Install & Configure PhpMyAdmin`
